### ISSUE TITLE
通过好友申请

### ISSUE THREAD

**Issue by hackjun** [Kaguya233qwq/WeWorkBot#1]
大佬有找到ntwork通过好友申请的方法吗

看到有通知，没有动作

# 新好友请求通知
MT_RECV_FRIEND_MSG = 11049

**Comment by Kaguya233qwq** [comment]
目前ntwork确实是只能接收好友申请事件，暂无通过好友申请的实现。但可参考原作者另一个项目ntchat，其中包含通过好友申请的api。https://github.com/billyplus/ntchat/blob/master/examples/auto_accept_friend_request.py

**Comment by hackjun** [comment]
感谢大佬

**Comment by cheungchazz** [comment]
> 感谢大佬

老哥，自动通过好友搞定了吗
