### ISSUE TITLE
接收图片调用wx_cdn_download一直报错

### ISSUE THREAD

**Issue by keysaim** [Kaguya233qwq/WeWorkBot#5]
一直报这个错：
2023-10-12 17:49:34,889 - WeWorkInstance - DEBUG - on recv message: {'data': {'error_code': -2}, 'extend': '3a9db1c8-c533-3ca6-994b-571c3dcd5882', 'type': 11171}

代码如下：
```python
            ret = wework.wx_cdn_download(cdn['url'], cdn['auth_key'], cdn['size'], local_path)
```

我看ntwork好像有0.1.3版本，不知道是不是版本的问题，我下载的是你提供的0.1.0

**Comment by Kaguya233qwq** [comment]
<img width="543" alt="image" src="https://github.com/Kaguya233qwq/WeWorkBot/assets/53631287/1415326d-4a1d-4edb-9cba-90239468db5d">

使用c2c类型进行下载，图片类型file_type=2

**Comment by keysaim** [comment]
> <img alt="image" width="543" src="https://user-images.githubusercontent.com/53631287/274820736-1415326d-4a1d-4edb-9cba-90239468db5d.png">
> 使用c2c类型进行下载，图片类型file_type=2

谢谢回复哈，但是我不是下载语音啊，也可以通过c2c下载吗？

**Comment by Kaguya233qwq** [comment]
改变type的值即可。具体是哪些数值对应什么文件类型可以自己0-9枚举



---原始邮件---
发件人: "Neil ***@***.***&gt;
发送时间: 2023年10月14日(周六) 晚上8:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kaguya233qwq/WeWorkBot] 接收图片调用wx_cdn_download一直报错 (Issue #5)




   使用c2c类型进行下载，图片类型file_type=2  
谢谢回复哈，但是我不是下载语音啊，也可以通过c2c下载吗？

**Comment by keysaim** [comment]
> 改变type的值即可。具体是哪些数值对应什么文件类型可以自己0-9枚举
> […](#)
> ---原始邮件--- 发件人: "Neil ***@***.***&gt; 发送时间: 2023年10月14日(周六) 晚上8:26 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Kaguya233qwq/WeWorkBot] 接收图片调用wx_cdn_download一直报错 (Issue #5) 使用c2c类型进行下载，图片类型file_type=2 谢谢回复哈，但是我不是下载语音啊，也可以通过c2c下载吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，感谢~

**Comment by Yukino0912** [comment]
那请问图片的file_id怎么得到呢

**Comment by keysaim** [comment]
> 那请问图片的file_id怎么得到呢

消息体里面有啊
